import { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import jsPDF from "jspdf";

const HEADER_RE = /^(?:\d+\.\s*)?([A-Z][A-Z0-9 /&()',.\-]{3,}):?$/;

/** Split memo text into [{title, body}] sections on numbered/uppercase
 *  header lines (mirrors the backend's split_memo_sections). */
function splitMemoSections(memo) {
  const sections = [];
  let title = null;
  let lines = [];

  for (const line of memo.split("\n")) {
    const match = line.trim().match(HEADER_RE);
    if (match) {
      if (title !== null || lines.length) {
        sections.push({ title, body: lines.join("\n").trim() });
      }
      title = match[1].trim().replace(/:$/, "");
      lines = [];
    } else {
      lines.push(line);
    }
  }
  if (title !== null || lines.length) {
    sections.push({ title, body: lines.join("\n").trim() });
  }

  if (!sections.some((s) => s.title)) return [{ title: null, body: memo.trim() }];
  return sections;
}

const CASE_STYLES = {
  BULL: { border: "border-l-success", bg: "bg-success/5", tag: "text-success", icon: "🐂" },
  BEAR: { border: "border-l-danger", bg: "bg-danger/5", tag: "text-danger", icon: "🐻" },
  BASE: { border: "border-l-sky-400", bg: "bg-sky-400/5", tag: "text-sky-400", icon: "⚖️" },
};

function caseType(title) {
  const upper = (title ?? "").toUpperCase();
  if (upper.includes("BULL")) return "BULL";
  if (upper.includes("BEAR")) return "BEAR";
  if (upper.includes("BASE")) return "BASE";
  return null;
}

// PDF color palette (RGB triples, matching the app's dark/gold theme)
const PDF_NAVY = [10, 14, 26]; // #0a0e1a
const PDF_GOLD = [240, 180, 41]; // #f0b429
const PDF_WHITE = [255, 255, 255];
const PDF_BODY_GRAY = [51, 51, 51];
const PDF_MUTED_GRAY = [120, 120, 120];
const PDF_DISCLAIMER_BG = [235, 235, 235];
const PDF_DISCLAIMER_TEXT = [90, 90, 90];

const DISCLAIMER_TEXT =
  "For informational and educational purposes only. Not investment advice. Data sourced from " +
  "public APIs and may be delayed or incomplete. Generated by a multi-agent AI system.";

/** Manual letter-spacing for the small-caps-style header kicker - jsPDF's
 *  base14 fonts don't support true small-caps or a charSpace option we can
 *  rely on, so we simulate it with plain ASCII spaces between characters. */
function letterSpaced(str) {
  return str.toUpperCase().split("").join(" ");
}

/** Build the research memo as a pure text/vector PDF - no canvas, no DOM
 *  capture. Draws a navy header banner, then flows each memo section
 *  (gold bold title + wrapped gray body) down the page with automatic
 *  pagination, and finishes with a disclaimer box pinned to the bottom
 *  of the last page and page numbers on every page. */
function buildMemoPdf({ ticker, companyName, reportDate, sections }) {
  const pdf = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  const pageBreakY = 270;
  const contentTopY = 20;

  // ---- Header banner ----
  const headerHeight = 36;
  pdf.setFillColor(...PDF_NAVY);
  pdf.rect(0, 0, pageWidth, headerHeight, "F");

  pdf.setTextColor(...PDF_WHITE);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(8);
  pdf.text(letterSpaced("Equity Research"), margin, 10);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.text(reportDate, pageWidth - margin, 10, { align: "right" });

  const tickerLabel = ticker || "";
  const badgeY = 18;
  const badgeHeight = 8;
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(11);
  const badgeWidth = pdf.getTextWidth(tickerLabel) + 6;
  pdf.setFillColor(...PDF_GOLD);
  pdf.roundedRect(margin, badgeY, badgeWidth, badgeHeight, 1.2, 1.2, "F");
  pdf.setTextColor(...PDF_NAVY);
  pdf.text(tickerLabel, margin + badgeWidth / 2, badgeY + badgeHeight / 2 + 1.5, { align: "center" });

  pdf.setTextColor(...PDF_WHITE);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(17);
  pdf.text(companyName || ticker || "", margin + badgeWidth + 5, badgeY + badgeHeight / 2 + 1.5);

  // thin gold rule below the header
  pdf.setDrawColor(...PDF_GOLD);
  pdf.setLineWidth(0.6);
  pdf.line(0, headerHeight, pageWidth, headerHeight);

  // ---- Body sections ----
  let y = headerHeight + 12;

  const ensureSpace = () => {
    if (y > pageBreakY) {
      pdf.addPage();
      y = contentTopY;
    }
  };

  sections.forEach(({ title, body }) => {
    if (title) {
      ensureSpace();
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(11);
      pdf.setTextColor(...PDF_GOLD);
      pdf.text(title.toUpperCase(), margin, y);
      y += 7;
    }

    if (body) {
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(10);
      pdf.setTextColor(...PDF_BODY_GRAY);
      const lines = pdf.splitTextToSize(body, contentWidth);
      lines.forEach((line) => {
        ensureSpace();
        pdf.text(line, margin, y);
        y += 5;
      });
    }

    y += 4; // gap between sections
  });

  // ---- Disclaimer box, pinned to the bottom of the last page ----
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(8);
  const disclaimerLines = pdf.splitTextToSize(DISCLAIMER_TEXT, contentWidth - 8);
  const disclaimerBoxHeight = 10 + disclaimerLines.length * 4.2;
  const disclaimerBoxY = pageHeight - 15 - disclaimerBoxHeight;

  if (y + 6 > disclaimerBoxY) {
    pdf.addPage();
  }

  pdf.setFillColor(...PDF_DISCLAIMER_BG);
  pdf.rect(margin, disclaimerBoxY, contentWidth, disclaimerBoxHeight, "F");
  pdf.setTextColor(...PDF_DISCLAIMER_TEXT);
  let dy = disclaimerBoxY + 7;
  disclaimerLines.forEach((line) => {
    pdf.text(line, margin + 4, dy);
    dy += 4.2;
  });

  // ---- Page numbers, bottom right of every page ----
  const totalPages = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(...PDF_MUTED_GRAY);
    pdf.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 8, { align: "right" });
  }

  return pdf;
}

export default function ResearchMemo({ data }) {
  const memo = data.memo_data?.memo ?? "";
  const reportDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const [isExporting, setIsExporting] = useState(false);

  if (!memo) {
    return <div className="text-gray-400">No research memo was generated for this analysis.</div>;
  }

  const sections = splitMemoSections(memo);
  const companyName = data.company_info?.company_name ?? data.ticker;

  const handleDownloadPdf = () => {
    if (isExporting) return;
    setIsExporting(true);
    try {
      const pdf = buildMemoPdf({ ticker: data.ticker, companyName, reportDate, sections });
      const safeTicker = (data.ticker || "TICKER").replace(/[^A-Z0-9]/gi, "");
      const fileDate = new Date().toISOString().slice(0, 10);
      pdf.save(`${safeTicker}_Equity_Research_${fileDate}.pdf`);
    } catch (err) {
      console.error("PDF export failed:", err);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="mx-auto max-w-4xl space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-extrabold text-gold">Research Memo</h1>
        <button
          onClick={handleDownloadPdf}
          disabled={isExporting}
          className="flex items-center gap-2 rounded-lg border border-navy-600 px-4 py-2 text-sm
                     text-gray-300 transition hover:border-gold hover:text-gold disabled:opacity-60"
        >
          {isExporting ? <Loader2 size={15} className="animate-spin" /> : <Download size={15} />}
          {isExporting ? "Generating PDF..." : "Download PDF"}
        </button>
      </div>

      <div className="rounded-2xl border border-navy-600 bg-navy-700 p-8 md:p-10">
        {/* Report header */}
        <div className="flex flex-wrap items-baseline justify-between gap-2 border-b-2 border-gold pb-5">
          <div>
            <div className="text-[11px] font-extrabold uppercase tracking-[0.3em] text-gold">
              {data.ticker} Equity Research
            </div>
            <div className="mt-1 text-xl font-extrabold text-white">{companyName}</div>
          </div>
          <div className="text-right text-xs text-gray-400">
            {reportDate}
            <br />
            Multi-Agent AI Research Desk
          </div>
        </div>

        {/* Sections */}
        {sections.map((section, i) => {
          const type = caseType(section.title);

          if (type) {
            const style = CASE_STYLES[type];
            return (
              <div
                key={i}
                className={`my-5 rounded-xl border border-navy-600 border-l-4 ${style.border} ${style.bg} p-5`}
              >
                <div className={`text-xs font-extrabold uppercase tracking-[0.15em] ${style.tag}`}>
                  {style.icon} {section.title}
                </div>
                <p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-gray-200">
                  {section.body}
                </p>
              </div>
            );
          }

          return (
            <div key={i}>
              {section.title && (
                <>
                  <hr className="my-5 border-t border-gold/40" />
                  <div className="text-sm font-bold uppercase tracking-wider text-gold">
                    {section.title}
                  </div>
                </>
              )}
              {section.body && (
                <p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-gray-200">
                  {section.body}
                </p>
              )}
            </div>
          );
        })}

        <hr className="my-6 border-t border-gold/40" />
        <p className="text-[11px] leading-relaxed text-gray-500">{DISCLAIMER_TEXT}</p>
      </div>
    </div>
  );
}
