import { Download } from "lucide-react";

const HEADER_RE = /^(?:\d+\.\s*)?([A-Z][A-Z0-9 /&()',.\-]{3,}):?$/;

/** Split memo text into [{title, body}] sections on numbered/uppercase
 *  header lines (mirrors the backend's split_memo_sections). */
function splitMemoSections(memo) {
  const sections = [];
  let title = null;
  let lines = [];

  for (const line of memo.split("\n")) {
    const match = line.trim().match(HEADER_RE);
    if (match) {
      if (title !== null || lines.length) {
        sections.push({ title, body: lines.join("\n").trim() });
      }
      title = match[1].trim().replace(/:$/, "");
      lines = [];
    } else {
      lines.push(line);
    }
  }
  if (title !== null || lines.length) {
    sections.push({ title, body: lines.join("\n").trim() });
  }

  if (!sections.some((s) => s.title)) return [{ title: null, body: memo.trim() }];
  return sections;
}

const CASE_STYLES = {
  BULL: { border: "border-l-success", bg: "bg-success/5", tag: "text-success", icon: "🐂" },
  BEAR: { border: "border-l-danger", bg: "bg-danger/5", tag: "text-danger", icon: "🐻" },
  BASE: { border: "border-l-sky-400", bg: "bg-sky-400/5", tag: "text-sky-400", icon: "⚖️" },
};

function caseType(title) {
  const upper = (title ?? "").toUpperCase();
  if (upper.includes("BULL")) return "BULL";
  if (upper.includes("BEAR")) return "BEAR";
  if (upper.includes("BASE")) return "BASE";
  return null;
}

export default function ResearchMemo({ data }) {
  const memo = data.memo_data?.memo ?? "";
  const reportDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  if (!memo) {
    return <div className="text-gray-400">No research memo was generated for this analysis.</div>;
  }

  const sections = splitMemoSections(memo);

  return (
    <div className="mx-auto max-w-4xl space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-extrabold text-gold">Research Memo</h1>
        <button
          title="PDF export coming soon"
          className="flex items-center gap-2 rounded-lg border border-navy-600 px-4 py-2 text-sm
                     text-gray-300 transition hover:border-gold hover:text-gold"
        >
          <Download size={15} />
          Download PDF
        </button>
      </div>

      <div className="rounded-2xl border border-navy-600 bg-navy-700 p-8 md:p-10">
        {/* Report header */}
        <div className="flex flex-wrap items-baseline justify-between gap-2 border-b-2 border-gold pb-5">
          <div>
            <div className="text-[11px] font-extrabold uppercase tracking-[0.3em] text-gold">
              {data.ticker} Equity Research
            </div>
            <div className="mt-1 text-xl font-extrabold text-white">
              {data.company_info?.company_name ?? data.ticker}
            </div>
          </div>
          <div className="text-right text-xs text-gray-400">
            {reportDate}
            <br />
            Multi-Agent AI Research Desk
          </div>
        </div>

        {/* Sections */}
        {sections.map((section, i) => {
          const type = caseType(section.title);

          if (type) {
            const style = CASE_STYLES[type];
            return (
              <div
                key={i}
                className={`my-5 rounded-xl border border-navy-600 border-l-4 ${style.border} ${style.bg} p-5`}
              >
                <div className={`text-xs font-extrabold uppercase tracking-[0.15em] ${style.tag}`}>
                  {style.icon} {section.title}
                </div>
                <p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-gray-200">
                  {section.body}
                </p>
              </div>
            );
          }

          return (
            <div key={i}>
              {section.title && (
                <>
                  <hr className="my-5 border-t border-gold/40" />
                  <div className="text-sm font-bold uppercase tracking-wider text-gold">
                    {section.title}
                  </div>
                </>
              )}
              {section.body && (
                <p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-gray-200">
                  {section.body}
                </p>
              )}
            </div>
          );
        })}

        <hr className="my-6 border-t border-gold/40" />
        <p className="text-[11px] leading-relaxed text-gray-500">
          For informational and educational purposes only. Not investment advice. Data sourced from
          public APIs and may be delayed or incomplete. Generated by a multi-agent AI system.
        </p>
      </div>
    </div>
  );
}
